### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by feynon**
Removed the unblocked sites as of Jun 11/2019.

### CODE REVIEW

**Review by ryzokuken — APPROVED** [review]
Then I guess it's just ports that are blocked as of today?

Could someone verify these?

**Comment by feynon** [comment]
Yeah, I tried HexChat and SMTP mail clients, they don't connect still. So yeah, it's just ports.

**Comment by feynon** [comment]
Sorry, the closed request happened by accident. I am currently in campus and can verify the ports for mentioned things in README.md ain't working as of now.

**Comment by sidntrivedi** [comment]
@shermisaurus did you try running any overthewire.org wargame recently? If not , please try bandits once, it will verify if ssh is working or not.

**Comment by feynon** [comment]
@sidntrivedi012 overthewire.org doesn't works. And also they seem to have changed the security service from cyberroam to SOPHOS, and that's why I think certain set of sites are unblocked now, different categories per se.

**Comment by sidntrivedi** [comment]
Ah, no problem. @ryzokuken I hope it is ready to be merged?

**Comment by ryzokuken** [comment]
@shermisaurus I’d like for someone to verify these before merging.

**Comment by sidntrivedi** [comment]
@ryzokuken I checked them. They all are working as of now on college internet.

**Comment by ryzokuken** [comment]
@sidntrivedi012 so it's just the ports then? I'll try to go in on monday to argue for the ports. I guess we can archive this repo in that case?

**Comment by sidntrivedi** [comment]
@ryzokuken I have not yet tested ssh. Will test it tomorrow and maybe send a PR if it has started working.

**Pull request merged**
