### PR TITLE
Added changes.

### PR DESCRIPTION
**Pull request by sidntrivedi**
Corrected punctuation and typos.

### CODE REVIEW

**Comment by sidntrivedi** [comment]
@ryzokuken PTAL.

**Comment by ryzokuken** [comment]
@tonystark97 already has a PR for this 😅

**Comment by sidntrivedi** [comment]
So,how can I commit in his PR?Do I have to only add the changes to be made.

**Comment by sidntrivedi** [comment]
Okay. Got it. :+1: Closing this PR now.

**Pull request closed without merging**
