### PR TITLE
Added SSH

### PR DESCRIPTION
**Pull request by sidntrivedi**

### CODE REVIEW

**Comment by darkHarry** [comment]
Hi! Is the port 2220 for bandit ?

**Comment by sidntrivedi** [comment]
Yes.Will bandit work on port 22?

**Comment by sidntrivedi** [comment]
I doubt 443 is not blocked as Facebook uses it.

**Review by ryzokuken — APPROVED** [review]
Looks good. Does it need a rebase?

**Comment by sidntrivedi** [comment]
Yes,it will be good to rebase it.

**Comment by sidntrivedi** [comment]
Any other specific port to be added?Like for Bandit it was 2220.

**Comment by darkHarry** [comment]
There are many ports to open when it comes to wargames for ex pwnable has different ports to connect to. So can't really say

**Comment by sidntrivedi** [comment]
@darkHarry Ok.

**Review by ryzokuken — APPROVED** [review]

**Pull request merged**
